version: "3.8"

services:
  litellm-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - STORE_MODEL_IN_DB=False
      - TELEMETRY=False
      - PORT=4000
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Authorization: Bearer sk-1234", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - litellm-network

  litellm-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_BACKEND_URL=http://litellm-backend:4000
    depends_on:
      - litellm-backend
    restart: unless-stopped
    networks:
      - litellm-network
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json

networks:
  litellm-network:
    driver: bridge 